### ISSUE TITLE
Are the Scanning Directions in Figure 4 of the paper mislabeled?

### ISSUE THREAD

**Issue by qixuema** [hustvl/DiG#1]
Hello,

I noticed that the Scanning Directions in Figure 4 might be mislabeled. Could you please confirm if this is the case?

![image](https://github.com/hustvl/DiG/assets/58554118/61aacc72-7001-42c4-87cb-ed6de5357488)

**Comment by lh-zhu** [comment]
Yes, thanks for your kind reminder. We will fix this in revision!
